// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8sz6cAB4z8cxT2nske0QjcSOS3X3qJWs',
    appId: '1:373602809260:web:24bba89478301a6bb4f609',
    messagingSenderId: '373602809260',
    projectId: 'sale-pipeline-business',
    authDomain: 'sale-pipeline-business.firebaseapp.com',
    storageBucket: 'sale-pipeline-business.firebasestorage.app',
    measurementId: 'G-28P9WRESCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1DfuA8Old1sTcKpGORhj5nyZFN3Joow',
    appId: '1:373602809260:android:78662e97ec732015b4f609',
    messagingSenderId: '373602809260',
    projectId: 'sale-pipeline-business',
    storageBucket: 'sale-pipeline-business.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5RNq7F-2CEGUuMf0C2aGI4dYcrIR6sbg',
    appId: '1:373602809260:ios:d21ef1da92638362b4f609',
    messagingSenderId: '373602809260',
    projectId: 'sale-pipeline-business',
    storageBucket: 'sale-pipeline-business.firebasestorage.app',
    iosBundleId: 'com.example.salePipelineBusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5RNq7F-2CEGUuMf0C2aGI4dYcrIR6sbg',
    appId: '1:373602809260:ios:d21ef1da92638362b4f609',
    messagingSenderId: '373602809260',
    projectId: 'sale-pipeline-business',
    storageBucket: 'sale-pipeline-business.firebasestorage.app',
    iosBundleId: 'com.example.salePipelineBusiness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8sz6cAB4z8cxT2nske0QjcSOS3X3qJWs',
    appId: '1:373602809260:web:bb368597738476fbb4f609',
    messagingSenderId: '373602809260',
    projectId: 'sale-pipeline-business',
    authDomain: 'sale-pipeline-business.firebaseapp.com',
    storageBucket: 'sale-pipeline-business.firebasestorage.app',
    measurementId: 'G-66CQZXV2BK',
  );
}
